server:
  port: 8080
spring:
  application:
    name: micro-service
eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://192.168.12.76:8761/eureka/
management:
  security:
    enabled: false