server:
  port: 8087
spring:
  application:
    name: micro-service-v1
  sleuth:
    enabled: true
    sampler:
      percentage: 1
eureka:
  instance:
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 5
    prefer-ip-address: true
    metadata-map:
      version: pre-prod
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
management:
  security:
    enabled: false

