server:
  port: 8080
spring:
  application:
    name: micro-service-v1
  sleuth:
    enabled: true
    sampler:
      percentage: 1
  zipkin:
    base-url: http://192.168.12.76:9411/
  profiles:
    active: dev
eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://192.168.12.76:18761/eureka/
management:
  security:
    enabled: false
iotlogging:
  app-force-to-console: true