server:
  port: 9000
spring:
  application:
    name: zuul-server
eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
management:
  security:
    enabled: false
logging:
  level:
    root: info
ribbon:
  eureka:
    enabled: true
  filter:
    metadata:
      enabled: true
  ReadTimeout: 50000
  ConnectTimeout: 50000
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 50000
